### ISSUE TITLE
An error occurred when i was running " ./run @mode=tables @data=u-1 @feat=all @train=1 -maxExamples train:100 dev:100"

### ISSUE THREAD

**Issue by jingjingdd** [NiteshMethani/PlotQA#1]
Exception in thread "main" java.lang.NumberFormatException: For input string: "tables.lambdadcs.LambdaDCSExecutor"
 at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
 at java.lang.Integer.parseInt(Integer.java:580)
 at java.lang.Integer.parseInt(Integer.java:615)
 at fig.basic.OptInfo.interpretValue(OptionsParser.java:155)
 at fig.basic.OptInfo.set(OptionsParser.java:344)
 at fig.basic.OptionsParser.parse(OptionsParser.java:771)
 at fig.exec.Execution.init(Execution.java:212)
 at fig.exec.Execution.runWithObjArray(Execution.java:330)
 at fig.exec.Execution.run(Execution.java:325)
 at edu.stanford.nlp.sempre.Main.main(Main.java:50)

How can I solve the problem ？I look forward to hearing from you

**Comment by lucas-g-cardoso** [comment]
I seemed to have the same problem.
What I did was a reset in the fig repoitory, which is inside SEMPRE repo.

Try to `cd [PATH_TO_SEMPRE]/fig`

then try running `git reset --hard 8a7714adae7038d9feb6433a926a98adab582cfd`

This will return fig's repository to a specific commit, in 2017. After that, my code ran as expected.
